-- CreateEnum
CREATE TYPE "Category" AS ENUM ('Feature Extraction');

-- CreateEnum
CREATE TYPE "IPFSProvider" AS ENUM ('LIGHTHOUSE', 'IPFS', 'INFURA', 'S3');

-- CreateTable
CREATE TABLE "users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "web3authId" STRING,
    "userName" STRING,
    "email" STRING,
    "password" STRING,
    "firstName" STRING,
    "lastName" STRING,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Model" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "description" STRING NOT NULL,
    "category" "Category"[],
    "trainingRequestId" INT4 NOT NULL,
    "cid" STRING NOT NULL,

    CONSTRAINT "Model_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DataStore" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "cid" STRING NOT NULL,
    "provider" "IPFSProvider" NOT NULL DEFAULT 'LIGHTHOUSE',

    CONSTRAINT "DataStore_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TrainingRequest" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "modelId" INT4 NOT NULL,
    "cid" STRING NOT NULL,
    "dataStoreId" INT4 NOT NULL,

    CONSTRAINT "TrainingRequest_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_userName_key" ON "users"("userName");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "DataStore_cid_key" ON "DataStore"("cid");

-- AddForeignKey
ALTER TABLE "Model" ADD CONSTRAINT "Model_trainingRequestId_fkey" FOREIGN KEY ("trainingRequestId") REFERENCES "TrainingRequest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Model" ADD CONSTRAINT "Model_cid_fkey" FOREIGN KEY ("cid") REFERENCES "DataStore"("cid") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TrainingRequest" ADD CONSTRAINT "TrainingRequest_cid_fkey" FOREIGN KEY ("cid") REFERENCES "DataStore"("cid") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TrainingRequest" ADD CONSTRAINT "TrainingRequest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
