name: Task
title: "task: "
description: Create a task for the project 
labels: ['task']

body:
  - type: markdown
    attributes:
      value: |
        Here is the task!
  - type: textarea
    id: description
    attributes:
      label: Task description
      description: A clear and concise description of the task
      value: |
        - [ ]  
    validations:
      required: true

  - type: input
    attributes: 
      label: Related Issues
      placeholder: |
        Relates #21
    validations:
      required: false