-- CreateEnum
CREATE TYPE "Category" AS ENUM ('Feature Extraction');

-- CreateEnum
CREATE TYPE "IPFSProvider" AS ENUM ('LIGHTHOUSE', 'IPFS', 'INFURA', 'S3');

-- CreateTable
CREATE TABLE "users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "web3authId" STRING,
    "userName" STRING,
    "email" STRING,
    "password" STRING,
    "firstName" STRING,
    "lastName" STRING,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "models" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "description" STRING NOT NULL,
    "category" "Category"[],
    "trainingRequestId" INT4 NOT NULL,
    "cid" STRING NOT NULL,

    CONSTRAINT "models_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "datastores" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "cid" STRING NOT NULL,
    "provider" "IPFSProvider" NOT NULL DEFAULT 'LIGHTHOUSE',

    CONSTRAINT "datastores_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "training_requests" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "modelId" INT4 NOT NULL,
    "cid" STRING NOT NULL,
    "dataStoreId" INT4 NOT NULL,

    CONSTRAINT "training_requests_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_userName_key" ON "users"("userName");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "datastores_cid_key" ON "datastores"("cid");

-- AddForeignKey
ALTER TABLE "models" ADD CONSTRAINT "models_trainingRequestId_fkey" FOREIGN KEY ("trainingRequestId") REFERENCES "training_requests"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "models" ADD CONSTRAINT "models_cid_fkey" FOREIGN KEY ("cid") REFERENCES "datastores"("cid") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_requests" ADD CONSTRAINT "training_requests_cid_fkey" FOREIGN KEY ("cid") REFERENCES "datastores"("cid") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "training_requests" ADD CONSTRAINT "training_requests_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
