name: E2E

on:
  push:
    branches:
      - main
    tags:
  pull_request:
    branches:
      - main
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  envfile: ${{secrets.ENV}}
  MODE: test
  NODE_ENV: testing

jobs:
  build-and-test:
    concurrency: db-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.6

      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 19
          check-latest: true

      - name: Write environment
        run: |
          echo $envfile > .env
          sed -i 's/ /\n/g' .env
          source .env

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: E2E
        run: npm run test:e2e
